Improve format version mismatch error in binary loader
The previous message would result in e.g. this when opening
a project in 3.2 after using the master branch:

ERROR: open: File format '3.4.0' is too new!
  Please upgrade to a new engine version:
  res://sourceModels/BoxTextured/Texture.material.
  At: core/io/resource_format_binary.cpp:879.

(cherry picked from commit e35bb04c53e977f7353e9f377076cef71aaa6b0b)
* See https://github.com/godotengine/godot/pull/42571/files